name: 📆 Commit Calendar

on:
  # Automatically run every Sunday at 1:10 AM IST (19:40 UTC)
  schedule:
    - cron: "40 19 * * 0"
  # Allow manual runs
  workflow_dispatch:
  # Run on push to default branches
  push:
    branches:
      - main
      - master

jobs:
  calendar-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.plugin.calendar.svg

          # Base settings
          user: dpvasani
          template: classic
          base: ""
          config_timezone: Asia/Calcutta

          # ✅ Commit Calendar Plugin
          plugin_calendar: yes
          plugin_calendar_limit: 0   # You can use 1, 0, or -1 as explained
