name: 📗 Classic Template

on:
  # Automatically run every day at 12:00 AM IST (18:30 UTC)
  schedule:
    - cron: "30 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  classic-template-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: assets/metrics.template.classic.svg

          # 📗 Template Settings
          user: dpvasani
          template: classic
          base: header, repositories
          config_timezone: Asia/Calcutta

          # Optional: You can include any other plugins here too
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
